version: '3'
services:
  mongodb:
    image: metdino/klubovidb
    container_name: mojaBazaSpremnik
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    command: --noauth